branch-defaults:
  main:
    environment: server-dev
global:
  application_name: server
  branch: null
  default_ec2_keyname: ProductionKeyPair
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
